### ISSUE TITLE
Tracking Issue: Hack for finding workspace root.

### ISSUE THREAD

**Issue by YoshikiTakashima** [model-checking/kani#1472]
As of <2022-08-08 Mon>, cargo does not provide any environment
variables that allow us to read the workspace root. Instead we make
our own with a hack given in
https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993

``` toml
[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
```

The above hack should be replaced when cargo implements this feature.

Relevant cargo issue: https://github.com/rust-lang/cargo/issues/3946
