### ISSUE TITLE
Kani does not allow duplicate flags in Cargo.toml

### ISSUE THREAD

**Issue by danielsn** [model-checking/kani#2025]
I wanted to include two c files in a Kani proof.  If i do 

```
cargo kani --c-lib a.c --c-lib b.c
```

it all works fine.  When I try to move this to the cargo toml,

```toml
[package.metadata.kani.flags]
enable-unstable = true
c-lib = a.c
c-lib = b.c
```

I get 
```
       Duplicate key `c-lib` in table `package.metadata.kani.flags`
```

Instead, I have to do this:

```toml
[package.metadata.kani.flags]
enable-unstable = true
c-lib = ["a.c", "b.c"]
```

If we allow duplicate arguments in the command-line, we should at least document how do to it in the toml (or maybe just accept duplicate in the toml also)
