### ISSUE TITLE
Kani compilation fails when running cargo kani in a proc macro crate with `crate-type` specified.

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#2038]
I tried this code:

```rust
// src/lib.rs
#[kani::proof]
fn noop() {}
```

```toml
# Cargo.toml
[package]
name = "proc_macro_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
crate-type = ["lib"]
proc-macro = true
path = "src/lib.rs"
```

using the following command line invocation:

```
cargo kani
```

with Kani version: 0.17.0

I expected to see this happen: Verification succeed or Kani fail with a reasonable error

Instead, this happened: Kani compilation fail:

```
   Compiling proc_macro_lib v0.1.0 (/tmp/lib-pmacro)
error: Unrecognized option: 'reachability'

error: could not compile `proc_macro_lib`
Error: cargo exited with status exit status: 101
```
