### ISSUE TITLE
Implement Markdown regression summary action

### ISSUE THREAD

**Issue by karkhaz** [model-checking/kani#2339]
Implement a benchcomp 'action' (previously called 'visualization') that prints out a Markdown-formatted summary of regressions.
This would be used when running benchcomp in a GitHub Action. The summary would appear in the logs, and GitHub also formats it on the run front page, allowing the user to browse the results and understand which benchmarks regressed.
Users would specify the action like this in their config file:
```yaml actions:
  - type: markdown_regression_summary
    checks:
      - metric: passed
        check: boolean_not
      - metric: runtime
        check: ratio
        max: 1.1
```
This says: perform two actions on the results of running the two variants. Check if the 'passed' metric has flipped from true to false or vice versa; and check that the ratio of new to old runtime does not exceed 1.1.
If any pair of results fail either of these checks, the action prints out a table or other summary of those pairs of results.
