### ISSUE TITLE
RFC: Other tool versions

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#2572]
Requested feature: Kani uses a bunch of other tools (engines, solvers, etc.) to do its job. At present, the only version being reported is CBMC's (and maybe some SAT solver through CBMC's output?), but it'd nicer to have versions for all the artifacts to be used printed after collecting harness metadata. What I'm considering now is something like this:

```
Versions:
 - engine: cbmc 5.89.0
 - solvers: minisat X.Y.Z, kissat A.B.C
 - viewer: ...
```

This would allow users to check all versions (except for Kani's version, unless we added it here) in a single place. However, we could also hide this information by default and enable it through `--verbose`.
Use case: Geared towards multi-harness verification in particular.
