### ISSUE TITLE
Latest kani version breaks CI job

### ISSUE THREAD

**Issue by tcharding** [model-checking/kani#3142]
Thanks for your tool!

We run `kani` daily in CI and also on each PR we run it with `cargo kani --codegen-only`.

Today the `--codegen-only` job broke. It looks like its something to do with the latest release of `kani` but I'm not sure why its turned up today when the release came out 10 days ago. 

The build warning we are seeing is:

```
error[E0658]: use of unstable library feature 'proc_macro_byte_character'
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.80/src/wrapper.rs:871:21
    |
871 |                     proc_macro::Literal::byte_character(byte)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
```

I tried using `kani v0.48.0` and the job succeeds.

Example of job failing: https://github.com/rust-bitcoin/rust-bitcoin/actions/runs/8682612259/job/23807404841#step:3:288
CI passing after version pinned: https://github.com/rust-bitcoin/rust-bitcoin/pull/2686

And this is how we are running the job:
```yaml
  Kani:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout your code.'
        uses: actions/checkout@v4

      - name: 'Kani build proofs'
        uses: model-checking/kani-github-action@v1.1
        with:
          args: '--only-codegen'
```
